apiVersion: v1

kind: Service

metadata:
  name: ws3d-animations-service
  labels:
    app: ws3d-animations-service

spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  selector:
    app: ws3d-animations-pod

