apiVersion: v1

kind: Service

metadata:
  name: ws3d-utils-service
  labels:
    app: ws3d-utils-service

spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5004
  selector:
    app: ws3d-utils-pod

