apiVersion: v1

kind: Service

metadata:
  name: ws3d-blender-service
  labels:
    app: ws3d-blender-service

spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  selector:
    app: ws3d-blender-pod


